-- AlterTable
ALTER TABLE "criminals" ALTER COLUMN "name" SET DATA TYPE VARCHAR(250),
ALTER COLUMN "criminal_record" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "nationality" SET DATA TYPE VARCHAR(100);
