GET http://localhost:3030 HTTP/1.1
###
POST http://localhost:3030/login HTTP/1.1
Content-Type: application/json

{
    "email": "maria@jpd.com",
    "password": "maria123"
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 113
etag: W/"71-XLjsYZDWaT2dj4kXzLTLb/7Souw"
date: Wed, 06 Nov 2024 18:45:42 GMT
connection: close
###
POST http://localhost:3030/students HTTP/1.1
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@jpd.com",
    "password": "maria123",
    "type": "M",
    "cpf": "74825745820"
}

HTTP/1.1 201  - Created
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 197
etag: W/"c5-Ud8NXFVkEcQcfEXtk6vwr5Voemg"
date: Wed, 06 Nov 2024 18:45:16 GMT
connection: close
###
GET http://localhost:3030/students HTTP/1.1
Authorization: a224e41b-15fa-46cd-9447-5742be7648ed

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 327
etag: W/"147-TmEo5l7H3MGWLka7OffuN+Bz9T0"
date: Wed, 06 Nov 2024 20:03:21 GMT
connection: close
###
GET http://localhost:3030/students/ad45431a-8627-4c4d-b506-3336b34ba2b0 HTTP/1.1
###
PUT http://localhost:3030/students/ad45431a-8627-4c4d-b506-3336b34ba2b0 HTTP/1.1
Content-Type: application/json

{
    "name": "Maria Silva",
    "age": 18
}
###
DELETE http://localhost:3030/students/2a00eae9-2a37-499b-b463-ad816689775e HTTP/1.1