POST http://localhost:6120/crimes HTTP/1.1
Content-Type: application/json

{
    "status": "Aguardando_investigar",
    "dateOfOccurrence": "2005-05-12T08:05:25Z",
    "caseNumber": "24587456885",
    "priority": "baixa",
    "criminalId": "a7227d49-566a-4dc0-9455-bce8f1125bc2"
}
###
GET http://localhost:6120/crimes?caseNumber HTTP/1.1
###
GET http://localhost:6120/crimes/bf3e12e3-1ea4-4d48-8041-fa2e81e6294e HTTP/1.1
###
PUT http://localhost:6120/crimes/bf3e12e3-1ea4-4d48-8041-fa2e81e6294e HTTP/1.1
Content-Type: application/json

{
    "status": "Resolvido",
    "priority": "alta",
    "witnesses": "João e Fernanda",
    "motivation": "Vingança"
}
###
DELETE http://localhost:6120/crimes/7fa74054-1b74-4fd7-b62e-59dfdce4421c HTTP/1.1